import os
while True:
	print("\033[0;32m"+"Installing.......")
	print("apt update & upgrade Installing.......")
	os.system("apt update")
	os.system("apt upgrade")
	print("python,python2,python3 Installing.......")
	os.system("pkg install python -y")
	os.system("pkg install python2 -y")
	os.system("pkg install python3 -y")
	print("git Installing.......")
	os.system("pkg install git -y")
	print("figlet Installing.......")
	os.system("pkg install figlet -y")
	print("cmatrix Installing.......")
	os.system("pkg install cmatrix -y")
	print("toilet Installing....... ")
	os.system("pkg install toilet -y")
	print(" nano Installing.......")
	os.system("pkg install nano -y")
	print("php Installing.......")
	os.system("pkg install php")
	print("pip'pip2 Installing.......")
	os.system("pkg install pip -y")
	os.system("pkg install pip2")
	print("requests Installing.......")
	os.system("pip2 install requests")
	print("future Installing.......")
	os.system("pip install future")
	print("ruby Installing.......")
	os.system("apt install ruby")
	print("openssh Installing.......")
	os.system("apt install openssh")
	print("wget Installing.......")
	os.system("apt install wget")
	print("curl Installing.......")
	os.system("apt install curl")
	print("proof Installing.......")
	os.system("apt install proof")
	print("storage Permission")
	os.system("termux-setup-storage")
	os.system("clear")
	os.system("cd")